import joblib
import pandas as pd

def industries():
    industries = ['Media', 'Application Platforms', 'Apps', 'Curated Web',
        'Software', 'Games', 'Biotechnology', 'Analytics', 'Mobile',
        'E-Commerce', 'Entertainment', 'Networking', 'Health and Wellness',
        'Internet Marketing', 'Education', 'Search', 'Art', 'Beauty',
        'Local Businesses', 'Cosmetics', 'Hospitality', 'Health Care',
        'Advertising', 'Coffee', 'Enterprise Software', 'Batteries', 'iOS',
        'Fashion', 'EdTech', 'Social Travel', 'Sports', 'Real Estate',
        'Audio', 'Health Diagnostics', 'unknown', 'Internet',
        'Local Search', 'Service Providers', 'Publishing',
        'Consumer Goods', 'Manufacturing', 'Augmented Reality', 'Finance',
        'Design', 'Public Transportation', 'Travel', 'Baby Accessories',
        'Designers', 'Cars', 'Clean Technology', 'Content', 'Chat',
        'Cloud Computing', 'Geospatial', 'Music Services', 'Doctors',
        'Social Media', 'Non Profit', 'Fitness', 'Landscaping',
        'Financial Services', 'Consumers', 'Digital Media', 'News',
        'Technology', 'Delivery', 'Big Data', 'Android',
        'Blogging Platforms', 'Customer Service', 'Hardware + Software',
        'Computers', 'Artificial Intelligence', 'Services', 'DIY',
        'Presentations', 'Ad Targeting', 'Credit Cards', 'Discounts',
        'Internet of Things', 'Cloud Infrastructure', 'SaaS', 'Messaging',
        'Collaboration', 'Interior Design', 'Energy', 'Transportation',
        'FinTech', 'Information Technology', 'Consumer Electronics',
        'Communities', 'Data Centers', 'Point of Sale', 'Enterprises',
        'Bitcoin', 'Project Management', 'Business Services', 'Babies',
        '3D', '3D Technology', 'Photography', '3D Printing', 'Alumni',
        'Drones', 'Automotive', 'Printing', 'Creative', 'Automated Kiosk',
        'Business Analytics', 'Music', 'Semiconductors', 'Web Hosting',
        'Cloud Data Services', 'Consulting', 'Game', 'Developer APIs',
        'App Marketing', 'Physical Security', 'Coupons', 'Security',
        'Databases', 'Flash Storage', 'Animal Feed', 'Creative Industries',
        'Machine Learning', 'Crowdfunding', 'Commercial Real Estate',
        'Online Travel', 'Web Design', 'Anything Capital Intensive',
        'Human Resources', 'Office Space', 'Pets', 'Aerospace',
        'Online Shopping', 'Distribution', 'Carbon', 'Career Management',
        'Leisure', 'Consumer Internet', 'Video', 'Food Processing',
        'Healthcare Services', 'Startups', 'Sales and Marketing',
        'Accounting', 'Browser Extensions', 'Information Services',
        'Concentrated Solar Power', 'B2B', 'Nanotechnology',
        'Social Network Media', 'Development Platforms', 'Bicycles',
        'Content Creators', 'Broadcasting', 'Brand Marketing',
        'Finance Technology', 'Home Decor', 'Crowdsourcing',
        'Digital Entertainment', 'Exercise', 'Contact Centers',
        'E-Commerce Platforms', 'SEO', 'Chemicals',
        'Innovation Engineering', 'Travel & Tourism', 'Limousines',
        'Hardware', 'Charity', 'Online Rental', 'Telecommunications',
        'Health Care Information Technology', 'Health and Insurance',
        'Oil & Gas', 'Audiobooks', 'Communications Infrastructure',
        'Distributors', 'Medical', 'Employment', 'M2M', 'Local',
        'Home Automation', 'Contact Management', 'Information Security',
        'Electrical Distribution', 'Content Discovery', 'All Students',
        'Engineering Firms', 'Events', 'Diagnostics',
        'Government Innovation', 'Pharmaceuticals', 'Clean Energy',
        'Logistics', 'Domains', 'Payments', 'Nonprofits',
        'Homeland Security', 'Big Data Analytics', 'Credit', 'Colleges',
        'Medical Devices', 'Construction', 'Internet Radio Market',
        'Legal', 'Public Relations', 'Self Development',
        'Employer Benefits Programs', 'Internet Service Providers',
        'Agriculture', 'Advertising Platforms', 'CRM', 'Data Integration',
        'Politics', 'Collectibles', 'Application Performance Monitoring',
        'Facebook Applications', 'Email', 'Real Time',
        'Comparison Shopping', 'Electronics', 'Mobile Security',
        'Cloud Management', 'Intellectual Property',
        'Marketing Automation', 'Material Science', 'Bio-Pharm',
        'Business Intelligence', 'Assisitive Technology', 'Auctions',
        'Child Care', 'Enterprise Search', 'Classifieds',
        'Content Delivery', 'Business Development', 'DOD/Military',
        'Archiving', 'Advice', 'Digital Signage', 'Industrial',
        'Advertising Exchanges', 'Cause Marketing',
        'Performance Marketing', 'Governments', 'Advanced Materials',
        'Renewable Energies', 'Human Resource Automation',
        'Adventure Travel', 'Insurance', 'Law Enforcement',
        'Advertising Networks', 'Brokers',
        'Embedded Hardware and Software', 'Gps', 'Direct Sales',
        'Robotics', 'Corporate Training', 'Furniture', 'Consumer Lending',
        'Ediscovery', 'Bridging Online and Offline', 'Marketplaces',
        'Brewing', 'Commodities', 'Online Scheduling',
        'Reviews and Recommendations', 'Gift Card',
        'Industrial Automation', 'Lasers', 'Weddings', 'Farming',
        'Tracking', 'Lifestyle', 'Developer Tools', 'Hotels', 'Algorithms',
        'Biomass Power Generation', 'Content Syndication',
        'Location Based Services', 'Loyalty Programs',
        'Business Productivity', 'Personalization', 'Match-Making',
        'Interface Design', 'iPhone', 'Retail', 'Banking',
        'Innovation Management', 'Console Gaming', 'Mining Technologies',
        'Hospitals', 'Risk Management', 'Network Security', 'Data Mining',
        'Craft Beer', 'Cloud Security', 'Charter Schools', 'Architecture',
        'Document Management', 'Consumer Behavior', 'Defense', 'Maps',
        'Specialty Chemicals', 'iPad', 'Journalism',
        'Communications Hardware', 'Fantasy Sports', 'Social Commerce',
        'Investment Management', 'BPO Services', 'Language Learning',
        'Boating Industry', 'Gambling', 'Active Lifestyle', 'Watch',
        'Wine And Spirits', 'Cannabis', 'Dietary Supplements', 'Cooking',
        'Estimation and Quoting', 'Environmental Innovation', 'Graphics',
        'Small and Medium Businesses', 'Electric Vehicles',
        'Specialty Foods', 'Restaurants', 'Kids', 'Energy Management',
        'Waste Management', 'Sensors', 'Fleet Management',
        'Commercial Solar', 'Energy Efficiency', 'Biometrics',
        'Recruiting', 'Incubators', 'Corporate Wellness', 'Angels',
        'Bioinformatics', 'Online Dating', 'Identity',
        'Collaborative Consumption', 'Email Marketing', 'VoIP', 'Biofuels',
        'Gold', 'Reputation', 'Film Production', 'Property Management',
        'Ticketing', 'Wireless', 'Enterprise Security',
        'Alternative Medicine', 'Real Estate Investors',
        'Social Fundraising', 'App Discovery', 'Productivity Software',
        'App Stores', 'Meeting Software', 'Entrepreneur', 'Opinions',
        'Cyber Security', 'Social Television', 'All Markets',
        'Corporate IT', 'Dental', 'Enterprise Application', 'Aquaculture',
        'Water', 'Billing', 'Fraud Detection', 'Gamification', 'CAD',
        'Therapeutics', 'Photo Sharing', 'Data Security',
        'Local Based Services', 'Data Privacy', 'Social Business',
        'Artists Globally', 'Fuels', 'Diabetes', 'Oil and Gas',
        'Intelligent Systems', 'Logistics Company', 'English-Speaking',
        'College Campuses', 'Intellectual Asset Management', 'Simulation',
        'Casual Games', 'Event Management', 'Educational Games',
        'Sporting Goods', 'Guides', 'Licensing', 'Film', 'Charities',
        'Identity Management', 'Home & Garden', 'Lead Generation',
        'Lead Management', 'Auto', 'Sales Automation',
        'Certification Test', 'Heavy Industry', 'Private School',
        'Minerals', 'Infrastructure', 'Entertainment Industry',
        'Public Safety', 'Life Sciences', 'IT Management', 'Open Source',
        'Mobile Software Tools', 'File Sharing', 'Mobile Commerce',
        'Families', 'Social Media Platforms', 'Lifestyle Products', 'ICT',
        'Custom Retail', 'Venture Capital', 'Clinical Trials',
        'Musical Instruments', 'Market Research', 'Wholesale', 'SNS',
        'Navigation', 'Video Games', 'Freelancers',
        'Deep Information Technology', 'Private Social Networking',
        'Career Planning', 'Internet Infrastructure', 'Organic Food',
        'Low Bid Auctions', 'Coworking', 'E-Books', 'Mobile Games',
        'Celebrity', 'Local Advertising', 'Realtors', 'Mobility',
        'FreetoPlay Gaming', 'Building Products', 'Customer Support Tools',
        'Genetic Testing', 'College Recruiting', 'Cyber',
        'Emerging Markets', 'Toys', 'Outsourcing',
        'General Public Worldwide', 'Gadget', 'Professional Services',
        'Service Industries', 'Direct Marketing', 'Groceries',
        'IT and Cybersecurity', 'Generation Y-Z', 'Outdoors', 'Fruit',
        'New Technologies', 'Recreation', 'Mobile Social', 'Shopping',
        'Social Bookmarking', 'EBooks', 'Comics', 'Image Recognition',
        'Non-Tech', 'Product Development Services', 'K-12 Education',
        'Spas', 'Soccer', 'Lifestyle Businesses', 'Mass Customization',
        'Product Design', 'Assisted Living', 'Wearables', 'Social News',
        'Rental Housing', 'Flash Sales', 'Mobile Payments', 'Trading',
        'Digital Rights Management', 'Staffing Firms',
        'Optical Communications', 'EDA Tools', 'Parking', 'Linux',
        'Energy Storage', 'Data Visualization', 'Elder Care',
        'Electronic Health Records', 'Baby Boomers', 'Cable',
        'Enterprise Hardware', 'Social Media Advertising',
        'Personal Finance', 'Video Streaming', 'Darknet',
        'Online Identity', 'Knowledge Management',
        'Business Information Systems', 'New Product Development',
        'Computer Vision', 'Health Services Industry', 'Email Newsletters',
        'Utilities', 'China Internet', 'Medical Professionals', 'Shoes',
        'Jewelry', 'Tea', 'Systems', 'Religion',
        'Online Video Advertising', 'PaaS', 'Parenting', 'Forums',
        'Civil Engineers', 'Air Pollution Control', 'Natural Gas Uses',
        'Predictive Analytics', 'Natural Language Processing',
        'Cloud-Based Music', 'Internet Technology', 'IaaS',
        'University Students', 'Web Development', 'Optimization', 'Fmcg',
        'Online Gaming', 'Pervasive Computing', 'Storage', 'Nightlife',
        'Lighting', 'Incentives', 'Adaptive Equipment',
        'Postal and Courier Services', 'Fertility', 'Enterprise 2.0',
        'Multi-level Marketing', 'Concerts', 'Data Center Automation',
        'Call Center Automation', 'P2P Money Transfer', 'mHealth',
        'Tourism', 'SexTech', 'Contests', 'Financial Exchanges',
        'Natural Resources', 'Data Center Infrastructure', 'Recycling',
        'Retail Technology', 'Humanitarian', 'Online Education',
        'Governance', 'Funeral Industry', 'Gift Exchange', 'Social CRM',
        'Mobile Health', 'Online Reservations', 'Privacy',
        'Mobile Devices', 'Professional Networking', 'Game Mechanics',
        'Field Support Services', 'Home Owners', 'Social + Mobile + Local',
        'Freemium', 'Mechanical Solutions', 'Peer-to-Peer',
        'Personal Branding', 'Mobile Video', 'Group SMS', 'Textiles',
        'Tutoring', 'Plumbers', 'Shipping', 'Supply Chain Management',
        'Photo Editing', 'Solar', 'B2B Express Delivery', 'Translation',
        'In-Flight Entertainment', 'Displays', 'Internet TV',
        'Skill Assessment', 'Gas', 'Semiconductor Manufacturing Equipment',
        'Clean Technology IT', 'Synchronization', 'Farmers Market',
        'Senior Citizens', 'Skill Gaming', 'Neuroscience',
        'Unmanned Air Systems', 'Green', 'Building Owners', 'Eyewear',
        'Human Computer Interaction', 'Fuel Cells', 'Demographies',
        'Social Media Marketing', 'Monetization', 'Racing',
        'Mobile Shopping', 'High Schools', 'Specialty Retail',
        'Home Renovation', 'Business Travelers', 'Mobile Analytics',
        'Speech Recognition', 'Training', 'Swimming', 'Hedge Funds',
        'Interest Graph', 'Social Games', 'Stock Exchanges', 'Oil',
        'Television', 'Registrars', 'Polling', 'Flowers',
        'Vending and Concessions', 'RFID', 'Personal Health',
        'Golf Equipment', 'Mobile Advertising', 'Handmade', 'Smart Grid',
        'Price Comparison', 'Biotechnology and Semiconductor',
        'Mobile Enterprise', 'Disruptive Models', 'Resorts',
        'Vacation Rentals', 'Portals', 'Search Marketing', 'Google Glass',
        'Group Buying', 'Web Browsers', 'High School Students',
        'Shared Services', 'Debt Collecting', 'Indoor Positioning',
        'Local Commerce', 'Video on Demand', 'Video Conferencing',
        'Early-Stage Technology', 'Organic', 'Nutrition',
        'Rapidly Expanding', 'High Tech', 'Theatre', 'Social Recruiting',
        'Web Tools', 'Infrastructure Builders',
        'Enterprise Resource Planning', 'Group Email', 'Edutainment',
        'Music Education', 'Mens Specific', 'Gift Registries',
        'Baby Safety', 'Renewable Tech', 'Social Media Management',
        'Lotteries', 'Green Consumer Goods', 'Cosmetic Surgery',
        'Face Recognition', 'Energy IT', 'Kinect', 'Homeless Shelter',
        'Space Travel', 'Moneymaking', 'Product Search', 'Universities',
        'Pre Seed', 'MicroBlogging', 'Physicians', 'Direct Advertising',
        'Senior Health', 'Procurement', 'QR Codes', 'Subscription Service',
        'Independent Pharmacies', 'Impact Investing', 'Sex Industry',
        'Psychology', 'Music Venues', 'Promotional',
        'Independent Music Labels', 'Women', 'Testing', 'GreenTech',
        'Mobile Infrastructure', 'Retirement', 'Enterprise Purchasing',
        'Subscription Businesses', 'Virtual Workforces', 'Personal Data',
        'Young Adults', 'Lingerie', 'Film Distribution', 'Surveys',
        'Water Purification', 'User Experience Design', 'Taxis', 'Indians',
        'Veterinary', 'Social Buying', 'Ride Sharing', 'Experience Design',
        'Musicians', 'Mobile Emergency&Health', 'Usability',
        'User Interface', 'Sponsorship', 'Productivity', 'Gay & Lesbian',
        'Q&A', 'Micro-Enterprises', 'Task Management']

    return sorted(industries)

def countries():
    countries = [
        'ALB', 'ARE', 'ARG', 'ARM', 'AUS', 'AUT', 'AZE', 'BAH', 'BEL', 'BGD', 'BGR', 'BHR', 'BLM', 'BLR', 'BLZ', 'BMU', 'BRA',
        'BRB', 'BRN', 'BWA', 'CAN', 'CHE', 'CHL', 'CHN', 'CIV', 'CMR', 'COL', 'CRI', 'CYM', 'CYP', 'CZE', 'DEU', 'DMA', 'DNK',
        'DOM', 'DZA', 'ECU', 'EGY', 'ESP', 'EST', 'FIN', 'FRA', 'GBR', 'GEO', 'GGY', 'GHA', 'GIB', 'GRC', 'GRD', 'GTM', 'HKG',
        'HND', 'HRV', 'HUN', 'IDN', 'IND', 'IRL', 'IRN', 'ISL', 'ISR', 'ITA', 'JAM', 'JEY', 'JOR', 'JPN', 'KAZ', 'KEN', 'KHM',
        'KNA', 'KOR', 'KWT', 'LAO', 'LBN', 'LIE', 'LKA', 'LTU', 'LUX', 'LVA', 'MAF', 'MAR', 'MCO', 'MDA', 'MEX', 'MKD', 'MLT',
        'MMR', 'MNE', 'MOZ', 'MUS', 'MYS', 'NGA', 'NIC', 'NLD', 'NOR', 'NPL', 'NZL', 'OMN', 'PAK', 'PAN', 'PER', 'PHL', 'POL',
        'PRI', 'PRT', 'PRY', 'PSE', 'QAT', 'ROM', 'RUS', 'RWA', 'SAU', 'SEN', 'SGP', 'SLV', 'SOM', 'SRB', 'SVK', 'SVN', 'SWE',
        'SYC', 'TAN', 'TGO', 'THA', 'TTO', 'TUN', 'TUR', 'TWN', 'UGA', 'UKR', 'URY', 'USA', 'UZB', 'VEN', 'VNM', 'ZAF', 'ZMB',
        'ZWE'
    ]
    return sorted(countries)

def states():
    states = [
        '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27',
        '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '37', '38', '39', '4', '40', '41', '42', '43', '44', '45',
        '46', '47', '48', '49', '5', '50', '51', '52', '53', '54', '55', '56', '57', '58', '59', '6', '60', '61', '62', '65',
        '66', '68', '7', '71', '72', '73', '75', '77', '78', '79', '8', '81', '82', '83', '86', '87', '88', '89', '9', '90',
        '91', '97', '98', '99', 'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'AB', 'AK', 'AL', 'AR', 'AZ', 'B1', 'B2',
        'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'B9', 'BC', 'C1', 'C2', 'C3', 'C5', 'C6', 'C7', 'C8', 'C9', 'CA', 'CO', 'CT', 'D2',
        'D3', 'D4', 'D5', 'D6', 'D7', 'D8', 'D9', 'DC', 'DE', 'E1', 'E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8', 'E9', 'F1', 'F2',
        'F4', 'F5', 'F7', 'F8', 'F9', 'FL', 'G1', 'G2', 'G3', 'G4', 'G5', 'G7', 'G8', 'GA', 'GU', 'H2', 'H3', 'H4', 'H5', 'H7',
        'H8', 'H9', 'HI', 'I2', 'I4', 'I5', 'I6', 'I7', 'I9', 'IA', 'ID', 'IL', 'IN', 'J1', 'J2', 'J3', 'J4', 'J5', 'J6', 'J7',
        'J8', 'J9', 'K2', 'K3', 'K4', 'K7', 'K8', 'KS', 'KY', 'L1', 'L3', 'L6', 'L7', 'L8', 'L9', 'LA', 'M2', 'M3', 'M4', 'M5',
        'M8', 'M9', 'MA', 'MB', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'N1', 'N2', 'N3', 'N4', 'N5', 'N7', 'NB', 'NC', 'ND',
        'NE', 'NH', 'NJ', 'NL', 'NM', 'NS', 'NU', 'NV', 'NY', 'O1', 'O2', 'O3', 'OH', 'OK', 'ON', 'OR', 'P1', 'P2', 'P3', 'P4',
        'P5', 'P6', 'P8', 'P9', 'PA', 'PE', 'Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'QC', 'R3', 'R6', 'RI', 'SC', 'SD', 'SK', 'T5',
        'T6', 'T7', 'T8', 'T9', 'TN', 'TX', 'U1', 'U3', 'U6', 'U8', 'UT', 'V1', 'V2', 'V3', 'V5', 'V6', 'V7', 'V8', 'V9', 'VA',
        'VI', 'VT', 'W1', 'W2', 'W3', 'W4', 'W5', 'W6', 'W9', 'WA', 'WE', 'WI', 'WV', 'WY', 'X1', 'X2', 'X3', 'X4', 'X5', 'X7',
        'Y1', 'Y2', 'Y4', 'Y5', 'Y6', 'Y7', 'Y9', 'Z1', 'Z3', 'Z7', 'Z8'
    ]
    return sorted(states)
